# config.py

# DATA PATHS (placeholders - update with actual paths)
TRAIN_DATA_PATH = '/path/to/disulfiNNate/train'
TEST_DATA_PATH = '/path/to/disulfiNNate/test'
VAL_DATA_PATH = '/path/to/disulfiNNate/val'

# GRAPH HYPERPARAMETERS
EDGE_DISTANCE_CUTOFF_A = 8.0
MAX_RESIDUES = 20
NBR_DISTANCE_CUTOFF_A = 12.0

# TRAINING HYPERPARAMETERS
DESIRED_POS_RATIO = 0.03
BATCH_SIZE = 32
EPOCHS = 100
LEARNING_RATE = 1e-4
EARLY_STOPPING_PATIENCE = 20

# MODEL OUTPUT
MODEL_SAVE_FILENAME = "disulfiNNate-model.keras"
