# config.py

#DATA PATHS
TRAIN_DATA_PATH = '/media/data/jri/cath_S40/train'
TEST_DATA_PATH = '/media/data/jri/cath_S40/test'
VAL_DATA_PATH = '/media/data/jri/cath_S40/val'

#GRAPH HYPERPARAMETERS
EDGE_DISTANCE_CUTOFF_A = 6.0
MAX_RESIDUES = 20
NBR_DISTANCE_CUTOFF_A = 10.0

#TRAINING HYPERPARAMETERS
DESIRED_POS_RATIO = 0.07
BATCH_SIZE = 32
EPOCHS = 500
LEARNING_RATE = 1e-4
EARLY_STOPPING_PATIENCE = 20

#MODEL OUTPUT
MODEL_SAVE_FILENAME = "v2.4-GAT-maskededges.keras"